WORDS = {
    "easy": [
        "apple", "bread", "candy", "dream", "flame",
        "house", "mouse", "light", "water", "happy",
        "chair", "table", "phone", "book", "door",
        "plant", "river", "cloud", "smile", "friend",
        "grass", "stone", "beach", "ocean", "music",
        "dance", "movie", "color", "shirt", "shoes",
        "train", "plane", "heart", "star", "moon",
        "fish", "bird", "tree", "flower", "rain",
        "game", "ball", "song", "food", "drink",
        "sleep", "walk", "talk", "read", "write",
        "child", "father", "mother", "sister", "brother",
        "grandma", "grandpa", "uncle", "aunt", "cousin",
        "teacher", "student", "doctor", "nurse", "pilot",
        "artist", "writer", "singer", "actor", "chef",
        "money", "clock", "key", "box", "gift",
        "road", "city", "town", "village", "country",
        "summer", "winter", "spring", "autumn", "weather",
        "sun", "wind", "snow", "ice", "fire",
        "dog", "cat", "lion", "tiger", "bear",
        "horse", "cow", "sheep", "pig", "chicken",
        "blue", "green", "yellow", "red", "black",
        "white", "purple", "orange", "brown", "pink",
        "one", "two", "three", "four", "five",
        "big", "small", "long", "short", "tall",
        "fast", "slow", "hot", "cold", "wet",
        "dry", "loud", "quiet", "soft", "hard",
        "open", "close", "start", "end", "play",
        "work", "eat", "drink", "sing", "laugh",
    ],
    "medium": [
        "python", "hangman", "jungle", "puzzle", "quartz",
        "bottle", "garden", "window", "mystic", "forest",
        "island", "mountain", "desert", "valley", "secret",
        "shadow", "whisper", "journey", "silence", "mirror",
        "planet", "rocket", "galaxy", "comet", "astronaut",
        "violin", "trumpet", "guitar", "piano", "melody",
        "statue", "painting", "artist", "sculpture", "museum",
        "history", "science", "language", "country", "city",
        "camera", "laptop", "keyboard", "monitor", "speaker",
        "bicycle", "scooter", "vehicle", "traffic", "bridge",
        "captain", "soldier", "pirate", "explorer", "inventor",
        "library", "theater", "stadium", "airport", "station",
        "oceanic", "tropical", "arctic", "savanna", "tundra",
        "horizon", "eclipse", "constellation", "universe", "meteor",
        "harmony", "rhythm", "symphony", "orchestra", "concert",
        "portrait", "landscape", "abstract", "gallery", "exhibit",
        "ancient", "medieval", "renaissance", "modern", "future",
        "biology", "chemistry", "physics", "astronomy", "geology",
        "grammar", "vocabulary", "sentence", "paragraph", "essay",
        "computer", "software", "hardware", "internet", "network",
        "avenue", "boulevard", "crescent", "driveway", "highway",
        "carriage", "locomotive", "submarine", "helicopter", "glider",
    ],
    "hard": [
        "awkward", "rhythms", "cryptic", "zephyr", "mnemonic",
        "quizzical", "xylophone", "juxtapose", "syndrome", "buffalo",
        "labyrinth", "ephemeral", "ubiquitous", "cacophony", "mellifluous",
        "idiosyncrasy", "serendipity", "vicissitude", "effervescent", "acquiesce",
        "belligerent", "capricious", "desiccate", "egregious", "fastidious",
        "garrulous", "hierarchy", "immutable", "jejune", "kudos",
        "lachrymose", "magnanimous", "nefarious", "obfuscate", "parsimonious",
        "querulous", "recalcitrant", "sagacious", "taciturn", "unctuous",
        "verisimilitude", "winsome", "xenophobia", "yearning", "zeitgeist",
        "anachronism", "circumlocution", "dichotomy", "equivocate", "fiduciary",
        "germane", "hedonism", "impetuous", "lugubrious", "machiavellian",
        "nonchalant", "ostentatious", "perfunctory", "quixotic", "rejuvenate",
        "superfluous", "tenuous", "ubiquitous", "vacillate", "whimsical",
        "antediluvian", "bombastic", "chicanery", "deleterious", "exacerbate",
        "fatuous", "gregarious", "histrionic", "insidious", "jingoistic",
        "kowtow", "lassitude", "meretricious", "nugatory", "omnipotent",
        "palpable", "ratiocination", "sycophant", "trenchant", "uxorious",
        "vituperate", "wary", "yokel", "zealous", "abnegate",
        "circumvent", "didactic", "effulgent", "fortuitous", " Hackneyed",
        "incipient", "laconic", "malinger", "obviate", "pedantic",
        "replete", "sardonic", "travesty", "umbrage", "vociferous",
    ]
}